spring:
  application:
    name: ecom-application
  #  jpa:
  #    show-sql: true
  #    hibernate:
  #      ddl-auto: create
  #  h2:
  #    console:
  #      enabled: true
  datasource:
    #PostgreSQL
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: kamil
    password: kamil
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
