spring:
  application:
    name: order-service
  datasource:
    #PostgreSQL
    url: jdbc:postgresql://localhost:5432/order
    username: kamil
    password: kamil
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083
