spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: classpath:/config
          search-locations: file:///E:\Programy\Github\nowy-ecomerce\nowy\ecom\configserver\src\main\resources\config
#          search-locations: file:///D:\GitHub\spirng-ecom-git\ecom\configserver\src\main\resources\config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"
server:
  port: 8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false